# Path for the TCL Trip Dataset.
tlc.dataset.filepath=C:/Users/Lenovo/Downloads/archive/yellow_tripdata_2015-01.csv

# Total number of parallel worker threads allocated to consume and process data rows.
worker.count=6

# The maximum bounds of the internal queue used to buffer inflated objects before processing.
queue.capacity=50000

# Poison pill to shut down the consumers.
poison.pill.string=poison pill